#!name = 京东比价
#!desc = 京东商品历史价格比较。
#!date = 2026-01-01 00:00:00
#!author = WeiGiegie[https://github.com/WeiGiegie]
#!ScriptURL = https://raw.githubusercontent.com/WeiGiegie/666/main/bijia.js

^https?:\/\/in\.m\.jd\.com\/product\/graphext\/\d+\.html url script-response-body https://raw.githubusercontent.com/pipix798/Scripts/main/JD_Price.js


hostname = in.m.jd.com
