#!name = 京东去广告
#!desc = 过滤京东开屏广告。
#!date = 2025-12-06 23:46:49
#!author = RuCu6[https://github.com/RuCu6] luestr[https://github.com/luestr]
#!ScriptURL = https://kelee.one/Tool/Loon/Lpx/JD_remove_ads.lpx

"^http:\/\/\w{32}\.jddebug\.com\/diagnose\?" url reject-200
https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(searchBoxWord|stationPullService|uniformRecommend[06]) url reject-dict
https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(deliverLayer|getTabHomeInfo|myOrderInfo|orderTrackBusiness|personinfoBusiness|start|welcomeHome) url script-response-body https://raw.githubusercontent.com/pipix798/Scripts/main/JD_remove_ads.js


hostname = api.m.jd.com
